Feature/logging
OkinawaOpenLaboratory/fiware-meteoroid pull request #14
Opened 2020-01-20 05:32 UTC by ryo-ma

The logs are output to /var/log/meteoroid/meteoroid.log and /var/log/meteoroid/error.log.
Then, I confirmed that logs are output in docker logs.

2020-01-20 08:21 UTC, YujiAzama requested changes
Thank you for your effort.
Please check the detailed point about PEP8.

2020-01-20 08:21 UTC, YujiAzama commented on meteoroid/core/libs/clients/open_whisk_client.py
> +import logging
The ideal order of the import syntax is as follows:
1. Python standard library
2. Third party library
3. Custom library

https://www.python.org/dev/peps/pep-0008/#id23

Can it be fixed as follows?
```
import json
import logging
import os

import requests
```

2020-01-20 08:21 UTC, YujiAzama commented on meteoroid/core/libs/clients/orion_subscription_client.py
> +import logging
ditto

2020-01-20 08:21 UTC, YujiAzama commented on meteoroid/core/libs/decorators.py
> +import logging
ditto

2020-01-20 08:21 UTC, YujiAzama commented on meteoroid/core/libs/faas_driver.py
> +import logging
ditto

2020-01-20 08:21 UTC, YujiAzama commented on meteoroid/meteoroid/check_environment.py
> +
Do you need one more empty line?

2020-01-20 08:49 UTC, YujiAzama approved these changes

2020-01-20 08:49 UTC, YujiAzama commented
lgtm.

2020-01-20 09:03 UTC, ryo-ma commented
The library you are looking for.

https://pypi.org/project/flake8-import-order/

2020-01-21 00:10 UTC, hhayashiool commented
Thank you for error handling function.
lgtm

2020-01-21 00:10 UTC, merged